# Generated by Django 6.0.7 on 2026-08-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customeraddress_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Customer addresses'},
        ),
        migrations.AlterModelOptions(
            name='customerhistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Customer histories'},
        ),
    ]
