# Generated by Django 6.1 on 2026-08-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
