# Generated by Django 6.0.7 on 2026-08-04 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.CharField(blank=True, choices=[('DHAKA_NORTH', 'Dhaka North'), ('DHAKA_SOUTH', 'Dhaka South'), ('CHATTOGRAM', 'Chattogram'), ('SYLHET', 'Sylhet')], default='', max_length=50)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('ON_JOB', 'On Job'), ('ON_LEAVE', 'On Leave'), ('OFFLINE', 'Offline')], default='AVAILABLE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'technician_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
