# Generated by Django 6.0.7 on 2026-08-04 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_replacementkitrequest'),
        ('technicians', '0002_technicianjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianjob',
            name='replacement_kit_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='installations.replacementkitrequest'),
        ),
        migrations.AlterField(
            model_name='technicianjob',
            name='installation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='installations.installationrequest'),
        ),
    ]
