# Generated by Django 6.0.7 on 2026-08-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0003_technicianjob_replacement_kit_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='technicians/profile/'),
        ),
    ]
