# Generated by Django 6.0.7 on 2026-08-06 07:37

import django.db.models.deletion
import shared.validators.phone_validator
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('booking_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, validators=[shared.validators.phone_validator.validate_phone])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('product_model_text', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('INSTALLATION', 'Installation'), ('REPAIR', 'Repair'), ('MAINTENANCE', 'Maintenance'), ('FILTER_REPLACEMENT', 'Filter Replacement'), ('WATER_QUALITY_CHECK', 'Water Quality Check'), ('GENERAL_SERVICE', 'General Service')], max_length=30)),
                ('division', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('full_address', models.TextField()),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='service_bookings/attachments/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_bookings', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'db_table': 'service_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBookingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='service_bookings.servicebooking')),
            ],
            options={
                'db_table': 'service_booking_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='service_bookings.servicebooking')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['booking_id'], name='service_boo_booking_ea7c58_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['status'], name='service_boo_status_43b712_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['phone'], name='service_boo_phone_91f8eb_idx'),
        ),
    ]
