# Generated by Django 6.0.7 on 2026-08-02 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='registrations/qrcodes/')),
                ('qr_code_data', models.CharField(blank=True, max_length=255)),
                ('installation_status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('warranty_status', models.CharField(choices=[('NOT_ACTIVATED', 'Not Activated'), ('ACTIVE', 'Active'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('TRANSFERRED', 'Transferred')], default='NOT_ACTIVATED', max_length=50)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('installation_address', models.TextField(blank=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_registrations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_products', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_registrations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='products.product')),
            ],
            options={
                'db_table': 'product_registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('REGISTERED', 'Registered'), ('INSTALLATION_SCHEDULED', 'Installation Scheduled'), ('TECHNICIAN_ASSIGNED', 'Technician Assigned'), ('INSTALLED', 'Installed'), ('WARRANTY_ACTIVATED', 'Warranty Activated'), ('SERVICE_BOOKED', 'Service Booked'), ('FILTER_REPLACED', 'Filter Replaced'), ('WARRANTY_EXPIRED', 'Warranty Expired'), ('WARRANTY_TRANSFERRED', 'Warranty Transferred'), ('NOTE', 'Note')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='product_registrations.productregistration')),
            ],
            options={
                'db_table': 'product_timeline_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productregistration',
            index=models.Index(fields=['customer'], name='product_reg_custome_150b37_idx'),
        ),
        migrations.AddIndex(
            model_name='productregistration',
            index=models.Index(fields=['warranty_status'], name='product_reg_warrant_737d27_idx'),
        ),
    ]
