# Generated by Django 6.0.7 on 2026-08-13 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_replacementkitrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISAPPROVED', 'Disapproved'), ('SCHEDULED', 'Scheduled'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('RESCHEDULED', 'Rescheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='replacementkitrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISAPPROVED', 'Disapproved'), ('SCHEDULED', 'Scheduled'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('RESCHEDULED', 'Rescheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.CreateModel(
            name='InstallationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='installations.installationrequest')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_installations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Installation histories',
                'db_table': 'installation_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
