# Generated by Django 6.0.7 on 2026-08-13 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0003_alter_installationrequest_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='installations.installationrequest')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'installation_checklists',
            },
        ),
        migrations.CreateModel(
            name='InstallationPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_type', models.CharField(choices=[('BEFORE', 'Before Installation'), ('AFTER', 'After Installation')], max_length=20)),
                ('photo', models.ImageField(upload_to='installations/photos/')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='installations.installationrequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_installation_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'installation_photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallationSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_image', models.ImageField(upload_to='installations/signatures/')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_signatures', to=settings.AUTH_USER_MODEL)),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='installations.installationrequest')),
            ],
            options={
                'db_table': 'installation_signatures',
            },
        ),
    ]
