from django.contrib import admin
from apps.accounts.models import User
from apps.accounts.admin import UserAdmin
from shared.constants.roles import UserRole
from apps.customers.models import CustomerProfile, CustomerAddress, CustomerNote, CustomerHistory
from apps.dealers.admin import DealerProfileInline, RegisteredCustomerInline, RegisteredProductInline, InstallationRequestInline

# ---------------------------------------------------------
# Inlines for Unified User Admin Dashboard
# ---------------------------------------------------------

class CustomerProfileInline(admin.StackedInline):
    model = CustomerProfile
    fk_name = "user"
    can_delete = False
    verbose_name_plural = "Customer Profile"

class CustomerAddressInline(admin.TabularInline):
    model = CustomerAddress
    extra = 0

class CustomerNoteInline(admin.TabularInline):
    model = CustomerNote
    fk_name = "customer"
    extra = 0

class CustomerHistoryInline(admin.TabularInline):
    model = CustomerHistory
    fk_name = "customer"
    extra = 0
    can_delete = False
    readonly_fields = ("event_type", "description", "performed_by", "created_at", "updated_at")

    def has_add_permission(self, request, obj=None):
        return False # History is read-only, generated by backend logic


# Safely Unregister the default UserAdmin and inject our Inlines
try:
    admin.site.unregister(User)
except admin.sites.NotRegistered:
    pass

@admin.register(User)
class CustomUserAdmin(UserAdmin):
    def get_inlines(self, request, obj=None):
        # Only inject these tables if the user is a CUSTOMER.
        # This keeps Dealer/Technician admin pages perfectly clean!
        if obj and obj.role == UserRole.CUSTOMER:
            return [
                CustomerProfileInline,
                CustomerAddressInline,
                CustomerNoteInline,
                CustomerHistoryInline
            ]
        elif obj and obj.role == UserRole.DEALER:
            return [
                DealerProfileInline, 
                RegisteredCustomerInline,
                RegisteredProductInline,
                InstallationRequestInline
            ]
        return super().get_inlines(request, obj)
