# Generated by Django 6.0.7 on 2026-08-06 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_chat_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant')], max_length=15)),
                ('content', models.TextField()),
                ('answered_by', models.CharField(blank=True, choices=[('DIRECT_PRODUCT_LOOKUP', 'Direct Product Lookup'), ('DIRECT_COMPARISON', 'Direct Comparison'), ('DIRECT_FAQ_MATCH', 'Direct FAQ Match'), ('LLM_GENERATED', 'LLM Generated')], max_length=30, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatsession')),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PRODUCT_INFO', 'Product Info'), ('PRICING', 'Pricing'), ('WARRANTY', 'Warranty'), ('INSTALLATION', 'Installation'), ('MAINTENANCE', 'Maintenance'), ('FILTER_REPLACEMENT', 'Filter Replacement'), ('SERVICE_CHARGES', 'Service Charges'), ('DELIVERY', 'Delivery'), ('GENERAL_FAQ', 'General FAQ'), ('RECOMMENDATION', 'Recommendation')], max_length=30)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_knowledge_base',
                'ordering': ['category', 'title'],
            },
        ),
    ]
