# Generated by Django 6.0.7 on 2026-08-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('INSTALLATION_ASSIGNED', 'Installation Assigned'), ('TECHNICIAN_ON_THE_WAY', 'Technician On The Way'), ('INSTALLATION_COMPLETED', 'Installation Completed'), ('SERVICE_REMINDER', 'Service Reminder'), ('WARRANTY_EXPIRY', 'Warranty Expiry'), ('FILTER_REPLACEMENT', 'Filter Replacement'), ('PAYMENT_SUCCESS', 'Payment Success'), ('REPLACEMENT_KIT_SHIPPED', 'Replacement Kit Shipped'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('IN_APP', 'In-App'), ('PUSH', 'Push Notification'), ('EMAIL', 'Email'), ('SMS', 'SMS')], default='IN_APP', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
