# Generated by Django 6.0.7 on 2026-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_event_type_notification_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('INSTALLATION_REQUESTED', 'Installation Requested'), ('INSTALLATION_APPROVED', 'Installation Approved'), ('INSTALLATION_SCHEDULED', 'Installation Scheduled'), ('INSTALLATION_ASSIGNED', 'Installation Assigned'), ('TECHNICIAN_ON_THE_WAY', 'Technician On The Way'), ('INSTALLATION_COMPLETED', 'Installation Completed'), ('SERVICE_REMINDER', 'Service Reminder'), ('WARRANTY_EXPIRY', 'Warranty Expiry'), ('FILTER_REPLACEMENT', 'Filter Replacement'), ('PAYMENT_SUCCESS', 'Payment Success'), ('REPLACEMENT_KIT_SHIPPED', 'Replacement Kit Shipped'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=50),
        ),
    ]
